import type { Product } from '../types/product';
import bracelet1 from '../assets/img/bracelets/bracelet1.jpg';
import bracelet2 from '../assets/img/bracelets/bracelet2.jpg';
import bracelet3 from '../assets/img/bracelets/bracelet3.jpg';
import bracelet4 from '../assets/img/bracelets/bracelet4.jpg';
import bracelet5 from '../assets/img/bracelets/bracelet5.jpg';
import bracelet6 from '../assets/img/bracelets/bracelet6.jpg';
import bracelet7 from '../assets/img/bracelets/bracelet7.jpg';
import bracelet8 from '../assets/img/bracelets/bracelet8.jpg';
import cufflinks1 from '../assets/img/cufflinks/cufflinks1.jpg';
import cufflinks2 from '../assets/img/cufflinks/cufflinks2.jpg';
import cufflinks3 from '../assets/img/cufflinks/cufflinks3.jpg';
import cufflinks4 from '../assets/img/cufflinks/cufflinks4.jpg';
import cufflinks5 from '../assets/img/cufflinks/cufflinks5.jpg';
import cufflinks6 from '../assets/img/cufflinks/cufflinks6.jpg';
import cufflinks7 from '../assets/img/cufflinks/cufflinks7.jpg';
import cufflinks8 from '../assets/img/cufflinks/cufflinks8.jpg';
import cufflinks9 from '../assets/img/cufflinks/cufflinks9.jpg';
import necklace1 from '../assets/img/necklaces/necklace1.jpg';
import necklace2 from '../assets/img/necklaces/necklace2.jpg';
import necklace3 from '../assets/img/necklaces/necklace3.jpg';
import necklace4 from '../assets/img/necklaces/necklace4.jpg';
import necklace5 from '../assets/img/necklaces/necklace5.jpg';
import necklace6 from '../assets/img/necklaces/necklace6.jpg';
import ring1 from '../assets/img/rings/ring1.jpg';
import ring2 from '../assets/img/rings/ring2.jpg';
import ring3 from '../assets/img/rings/ring3.jpg';
import ring4 from '../assets/img/rings/ring4.jpg';
import ring5 from '../assets/img/rings/ring5.jpg';
import ring6 from '../assets/img/rings/ring6.jpg';
import ring7 from '../assets/img/rings/ring7.jpg';
import ring8 from '../assets/img/rings/ring8.jpg';
import ring10 from '../assets/img/rings/ring10.jpg';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    nameKey: 'goldPrestigeBracelet',
    category: 'bracelets',
    collections: ['prestige'],
    material: ['yellowGold', 'leather'],
    stone: ['diamond'],
    gender: 'men',
    price: 3500,
    currency: 'USD',
    image: bracelet1,
    inStock: true,
  },
  {
    id: '2',
    nameKey: 'platinumSignatureBracelet',
    category: 'bracelets',
    collections: ['signature'],
    material: ['platinum', 'leather'],
    stone: [],
    gender: 'men',
    price: 250,
    currency: 'USD',
    image: bracelet2,
    inStock: true,
  },
  {
    id: '3',
    nameKey: 'diamondPrestigeBracelet',
    category: 'bracelets',
    collections: ['prestige'],
    material: ['yellowGold', 'whiteGold', 'leather'],
    stone: ['diamond'],
    gender: 'men',
    price: 3100,
    currency: 'USD',
    image: bracelet5,
    inStock: true,
  },
  {
    id: '4',
    nameKey: 'beadedSignatureBracelet',
    category: 'bracelets',
    collections: ['signature'],
    material: ['beaded', 'silver'],
    stone: [],
    gender: 'men',
    price: 120,
    currency: 'USD',
    image: bracelet4,
    inStock: true,
  },
  {
    id: '5',
    nameKey: 'leatherTimelessBracelet',
    category: 'bracelets',
    collections: ['timeless'],
    material: ['leather', 'silver'],
    stone: [],
    gender: 'men',
    price: 100,
    currency: 'USD',
    image: bracelet3,
    inStock: true,
  },
  {
    id: '6',
    nameKey: 'goldChainTimelessBracelet',
    category: 'bracelets',
    collections: ['timeless'],
    material: ['whiteGold'],
    stone: ['diamond'],
    gender: 'men',
    price: 1700,
    currency: 'USD',
    image: bracelet6,
    inStock: true,
  },
  {
    id: '7',
    nameKey: 'silverTimelessBracelet',
    category: 'bracelets',
    collections: ['timeless'],
    material: ['silver', 'leather'],
    stone: [],
    gender: 'men',
    price: 175,
    currency: 'USD',
    image: bracelet7,
    inStock: true,
  },
  {
    id: '8',
    nameKey: 'gemstonePrestigeBracelet',
    category: 'bracelets',
    collections: ['prestige'],
    material: ['whiteGold', 'leather'],
    stone: ['diamond'],
    gender: 'men',
    price: 6200,
    currency: 'USD',
    image: bracelet8,
    inStock: true,
  },
  {
    id: '9',
    nameKey: 'goldTimelessCufflinks',
    category: 'cufflinks',
    collections: ['timeless'],
    material: ['yellowGold', 'whiteGold'],
    stone: [],
    gender: 'men',
    price: 320,
    currency: 'USD',
    image: cufflinks1,
    inStock: true,
  },
  {
    id: '10',
    nameKey: 'silverSignatureCufflinks',
    category: 'cufflinks',
    collections: ['signature'],
    material: ['silver'],
    stone: ['swarovski'],
    gender: 'men',
    price: 130,
    currency: 'USD',
    image: cufflinks2,
    inStock: true,
  },
  {
    id: '11',
    nameKey: 'goldSilverTimelessCufflinks',
    category: 'cufflinks',
    collections: ['timeless'],
    material: ['silver', 'yellowGold'],
    stone: [],
    gender: 'men',
    price: 120,
    currency: 'USD',
    image: cufflinks3,
    inStock: true,
  },
  {
    id: '12',
    nameKey: 'pearlSignatureCufflinks',
    category: 'cufflinks',
    collections: ['signature'],
    material: ['roseGold'],
    stone: ['pearl'],
    gender: 'men',
    price: 200,
    currency: 'USD',
    image: cufflinks4,
    inStock: true,
  },
  {
    id: '13',
    nameKey: 'diamondPrestigeCufflinks',
    category: 'cufflinks',
    collections: ['prestige'],
    material: ['yellowGold'],
    stone: ['diamond'],
    gender: 'men',
    price: 2100,
    currency: 'USD',
    image: cufflinks5,
    inStock: true,
  },
  {
    id: '14',
    nameKey: 'silverLazuliCufflinks',
    category: 'cufflinks',
    collections: ['signature'],
    material: ['silver'],
    stone: ['lazuli'],
    gender: 'men',
    price: 110,
    currency: 'USD',
    image: cufflinks6,
    inStock: true,
  },
  {
    id: '15',
    nameKey: 'silverTimelessCufflinks',
    category: 'cufflinks',
    collections: ['timeless'],
    material: ['silver', 'roseGold'],
    stone: [],
    gender: 'men',
    price: 110,
    currency: 'USD',
    image: cufflinks7,
    inStock: true,
  },
  {
    id: '16',
    nameKey: 'bicolorPrestigeCufflinks',
    category: 'cufflinks',
    collections: ['prestige'],
    material: ['silver', 'yellowGold'],
    stone: ['swarovski'],
    gender: 'men',
    price: 400,
    currency: 'USD',
    image: cufflinks8,
    inStock: true,
  },
  {
    id: '17',
    nameKey: 'bicolorTimelessCufflinks',
    category: 'cufflinks',
    collections: ['timeless'],
    material: ['whiteGold', 'yellowGold'],
    stone: [],
    gender: 'men',
    price: 220,
    currency: 'USD',
    image: cufflinks9,
    inStock: true,
  },
  {
    id: '18',
    nameKey: 'silverSignatureNecklace',
    category: 'necklaces',
    collections: ['signature'],
    material: ['silver'],
    stone: [],
    gender: 'men',
    price: 260,
    currency: 'USD',
    image: necklace1,
    inStock: true,
  },
  {
    id: '19',
    nameKey: 'roseGoldSignatureNecklace',
    category: 'necklaces',
    collections: ['signature'],
    material: ['roseGold', 'silver', 'leather'],
    stone: ['swarovski'],
    gender: 'men',
    price: 320,
    currency: 'USD',
    image: necklace2,
    inStock: true,
  },
  {
    id: '20',
    nameKey: 'swarovskiSignatureNecklace',
    category: 'necklaces',
    collections: ['signature'],
    material: ['silver'],
    stone: ['swarovski'],
    gender: 'men',
    price: 320,
    currency: 'USD',
    image: necklace3,
    inStock: true,
  },
  {
    id: '21',
    nameKey: 'biGoldLeatherNecklace',
    category: 'necklaces',
    collections: ['signature'],
    material: ['yellowGold', 'whiteGold', 'leather'],
    stone: [],
    gender: 'men',
    price: 350,
    currency: 'USD',
    image: necklace4,
    inStock: true,
  },
  {
    id: '22',
    nameKey: 'crossPrestigeNecklace',
    category: 'necklaces',
    collections: ['prestige'],
    material: ['silver', 'yellowGold'],
    stone: [],
    gender: 'men',
    price: 750,
    currency: 'USD',
    image: necklace5,
    inStock: true,
  },
  {
    id: '23',
    nameKey: 'beBetterSignatureNecklace',
    category: 'necklaces',
    collections: ['signature'],
    material: ['silver'],
    stone: [],
    gender: 'men',
    price: 350,
    currency: 'USD',
    image: necklace6,
    inStock: true,
  },
  {
    id: '24',
    nameKey: 'goldPrestigeRing',
    category: 'rings',
    collections: ['prestige'],
    material: ['whiteGold'],
    stone: ['diamond'],
    gender: 'men',
    price: 2800,
    currency: 'USD',
    image: ring1,
    inStock: true,
  },
  {
    id: '25',
    nameKey: 'diamondPrestigeRing',
    category: 'rings',
    collections: ['prestige'],
    material: ['yellowGold', 'whiteGold'],
    stone: ['diamond'],
    gender: 'men',
    price: 2200,
    currency: 'USD',
    image: ring2,
    inStock: true,
  },
  {
    id: '26',
    nameKey: 'silverSignatureRing',
    category: 'rings',
    collections: ['signature'],
    material: ['silver'],
    stone: ['swarovski'],
    gender: 'men',
    price: 200,
    currency: 'USD',
    image: ring3,
    inStock: true,
  },
  {
    id: '27',
    nameKey: 'emeraldPrestigeRing',
    category: 'rings',
    collections: ['prestige'],
    material: ['whiteGold'],
    stone: ['emerald', 'diamond'],
    gender: 'men',
    price: 6000,
    currency: 'USD',
    image: ring4,
    inStock: true,
  },
  {
    id: '28',
    nameKey: 'silverSwarovskiRing',
    category: 'rings',
    collections: ['signature'],
    material: ['silver'],
    stone: ['swarovski'],
    gender: 'men',
    price: 350,
    currency: 'USD',
    image: ring5,
    inStock: true,
  },
  {
    id: '29',
    nameKey: 'yellowGoldWeddingRing',
    category: 'rings',
    collections: ['wedding'],
    material: ['yellowGold'],
    stone: ['diamond'],
    gender: 'men',
    price: 800,
    currency: 'USD',
    image: ring6,
    inStock: true,
  },
  {
    id: '30',
    nameKey: 'whiteGoldWeddingRing',
    category: 'rings',
    collections: ['wedding'],
    material: ['whiteGold'],
    stone: ['diamond'],
    gender: 'men',
    price: 700,
    currency: 'USD',
    image: ring7,
    inStock: true,
  },
  {
    id: '31',
    nameKey: 'sapphirePrestigeRing',
    category: 'rings',
    collections: ['prestige'],
    material: ['roseGold'],
    stone: ['sapphire', 'diamond'],
    gender: 'men',
    price: 1200,
    currency: 'USD',
    image: ring8,
    inStock: true,
  },
  {
    id: '32',
    nameKey: 'crossRingSignature',
    category: 'rings',
    collections: ['signature'],
    material: ['whiteGold'],
    stone: ['swarovski'],
    gender: 'men',
    price: 920,
    currency: 'USD',
    image: ring10,
    inStock: true,
  },
];
